dataPlane:
  adminUser:
    username: "admin"
    email: "admin@example.com" # required for password reset
    firstName: Admin
    lastName: Admin
    temporaryPassword: "admin" # you will be prompted to change this on first login

istioGateway:
  enabled: true
  # if you want to enable TLS, set the tlsCertSecretName
  # name of the secret with certificates. Secret should contain 2 files: tls.crt and tls.key
  # if redirectHttpToHttps is set to true, this secret must be provided to handle https traffic
  tlsCertSecretName: ""

spark:
  logLevel: warn

jupyter:
  authToken: ""

keycloak:
  enabled: true
  adminUser: "kc_admin"
  adminPassword: "Admin_123"
  # if adminPasswordSecret is set, the password will be read from the secret
  adminPasswordSecret: {}
    # name: secret-name
    # key: password
  # Change this if enabled is set to false, or controlPlane is enabled
  endpoint: "http://keycloak-http/auth"

storage:
  catalogs:
    spark_catalog:
      bucketName: lakehouse
  assetsBucketName: "assets"
  # minio, dell_ecs, aws_s3, gcs, azure_gen1, azure_gen2
  type: "minio"
  dellEcsSettings: {} # same as minioSettings
  minioSettings: {}
    # endpoint: "http://minio.default.svc.cluster.local:9000"
    # accessKey: "admin"
    # secretKey: "password"
    # # if secretKeySecret is set, the secretKey will be read from the secret
    # secretKeySecret: {}
    #   # name: secret-name
    #   # key: secret-key
  azureSettings: {}
      # storageAccountName: ""
      # storageAccountKey: ""
  additionalConfigOverrides: {}
     # coreSiteProperties: |
      # fs.s3a.path.style.test: true
      # fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    # sparkProperties: |
      # spark.sql.datetime.java8API.enabled: false

database:
  host: "mysql"
  port: "3306"
  user: "iomete_user"
  password: "iomete_pass"
  # if passwordSecret is set, the password will be read from the secret
  passwordSecret: {}
    # name: byo-db-creds
    # key: password
  prefix: "iomete_" # all IOMETE databases should be prefixed with this. See database init script.

  # Provide database admin credentials to create the IOMETE databases, otherwise please run the database init script manually.
  adminCredentials: {}
    # user: "root"
    # password: "onXB8UbEqYzkQFgbXe8F#C5ckmyKix&"
    # # if passwordSecret is set, the password will be read from the secret
    # passwordSecret: {}
    #   # name: byo-db-creds
    #   # key: password

clusterDomain: cluster.local
